# vim: ts=2 sw=2
language: cpp
before_install:
  - wget https://people.mozilla.org/~sstangl/mozjs-31.5.0.tar.bz2
  - tar xvf mozjs-31.5.0.tar.bz2
  - cd mozjs-31.5.0
  - cd js/src
  - ./configure && make -j1
  - make install
script:
  - python setup.py test
deploy:
  provider: pypi
  user: jiojiajiu
  password:
    secure: bT3FgmffHFMmWjSQ2EGln5hvKOtWU3jviJbN4e6ApGBIagmRsGgp7cFguhJUzYxuwptIScYymMtIgN8B5cucvADHNYKVJ/3yIPf0Fpv7TUlSHoybnVnc2gMLtTSsOikZuSzeXkhva16eKHN80UjV7jSiaB0hPtL4J5T7OkU9XEc=
  on:
    tags: true
    repo: new-mind/pyjs
