# vim: ts=2 sw=2
language: cpp
before_install:
  - ./setup.sh --download
  - ./setup.sh --build
  - ./setup.sh --install
  - export PATH=`./setup.sh --path`
script:
  - python setup.py test
deploy:
  provider: pypi
  user: jiojiajiu
  password:
    secure: bT3FgmffHFMmWjSQ2EGln5hvKOtWU3jviJbN4e6ApGBIagmRsGgp7cFguhJUzYxuwptIScYymMtIgN8B5cucvADHNYKVJ/3yIPf0Fpv7TUlSHoybnVnc2gMLtTSsOikZuSzeXkhva16eKHN80UjV7jSiaB0hPtL4J5T7OkU9XEc=
  on:
    tags: true
    repo: new-mind/pyjs
