language:
    - cpp
compiler: clang
env:
    - MOZJS_PYTHON=python2.7
before_install:
    - bash setup.sh --download
    - bash setup.sh --build
    - bash setup.sh --install
script:
    - python setup.py test
